//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinPFGW.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WINPFGW_DIALOG              102
#define IDS_WINPFGW_VERSION_STRING      102
#define IDR_MAINFRAME                   128
#define IDI_ICON_GREEN                  128
#define IDR_MAIN_MENU                   129
#define IDR_TRAY_MENU                   130
#define IDD_MESSAGE_DIALOG              132
#define IDD_TEXTVIEWER_DIALOG           133
#define IDI_ICON_RED                    134
#define IDI_ICON_YELLOW                 135
#define IDD_RANGE_COMPLETE              136
#define IDC_BTN_START                   1000
#define IDC_BTN_CONTINUE                1001
#define IDC_EDT_NSTART                  1002
#define IDC_EDT_KSTART                  1003
#define IDC_EDT_NEND                    1004
#define IDC_EDT_KEND                    1005
#define IDC_EDT_NSTEP                   1006
#define IDC_EDT_KSTEP                   1007
#define IDC_MODE_MESSAGE                1008
#define IDC_BTN_NMIN                    1009
#define IDC_BTN_KMIN                    1010
#define IDC_STATIC_CUR_NVALUE           1011
#define IDC_STATIC_CUR_KVALUE           1012
#define IDC_RADIO_HIGH_PRIORITY         1013
#define IDC_RADIO_NORM_PRIORITY         1014
#define IDC_RADIO_LOW_PRIORITY          1015
#define IDC_LISTBOX_OUTPUT              1016
#define IDC_STATIC_DIGITS               1017
#define IDC_EDT_B                       1018
#define IDC_EDIT_W                      1018
#define IDC_EDT_B2                      1019
#define IDC_EDIT_X                      1019
#define IDC_EDT_B3                      1020
#define IDC_EDIT_Y                      1020
#define IDC_EDT_B4                      1021
#define IDC_EDIT_Z                      1021
#define IDC_BTN_INPUTFILE               1022
#define IDC_BTN_OUTPUTFILE              1023
#define IDC_EDIT_INPUTFILE              1024
#define IDC_EDIT_OUTPUTFILE             1025
#define IDC_EDIT_OUTPUT                 1026
#define IDC_STATIC_N                    1027
#define IDC_STATIC_K                    1028
#define IDC_STATIC_NSTEP                1029
#define IDC_STATIC_KSTEP                1030
#define IDC_STATIC_W                    1031
#define IDC_STATIC_X                    1032
#define IDC_STATIC_Y                    1033
#define IDC_STATIC_Z                    1034
#define IDC_STATIC_NTO                  1035
#define IDC_STATIC_KTO                  1036
#define IDC_INPUT_FILE_BROWSE           1037
#define IDC_VERBOSE                     1038
#define IDC_FACTOR                      1039
#define IDC_TEST_P1                     1040
#define IDC_TEST_M1                     1041
#define IDC_TEST_PM1                    1042
#define IDC_FERMAT_FACTOR               1043
#define IDC_CHECK1                      1044
#define IDC_MESSAGE_TEXT                1045
#define IDC_LINE_IN_FILE                1046
#define IDC_TEXTVIEW_EDIT               1047
#define IDC_VIEW_PFGWDOC_TXT            1048
#define IDC_VIEW_ABCFILEFORMAT_TXT      1049
#define IDC_VIEW_NETWORKFILE2FORMAT_TXT 1050
#define IDC_VIEW_README_PFGW            1051
#define IDC_VIEW_AUTHORS                1052
#define IDC_VIEW_NEWS                   1053
#define IDC_VIEW_LICENSCE_PFGW          1054
#define IDC_VIEW_MANIFEST               1055
#define IDC_VIEW_OPENPFGW               1056
#define IDC_VIEW_RELNOTES               1057
#define IDC_VIEW_NEWPGENFORMATS_TXT     1058
#define IDC_VIEW_SCRIPTFORMAT_TXT       1059
#define IDC_PRINT_HELPPAGE              1061
#define IDC_STATIC_WINPFGW_VERSION      1062
#define IDC_STATIC_WOLTMAN_VERSION      1064
#define IDC_STATIC_PFGW_VERSION         1065
#define IDC_STANDARD_TEST               32771
#define IDC_FROM_FILE_TEST              32772
#define IDC_VERIFYER_TEST               32773
#define IDC_PROTH_PRIME_INPUT           32774
#define IDC_Nm1_PRIME_INPUT             32775
#define IDC_AUTOMACTIC_PROOFCHOICE      32776
#define IDC_PRP_PROOFCHOICE             32777
#define IDC_Nm1_PROOFCHOICE             32778
#define IDC_Np1_PROOFCHOICE             32779
#define IDC_CONTINUE_TESTS              32780
#define IDC_FACTORIZE_ONLY              32781
#define IDC_DECIMAL_EXPANSION           32782
#define IDC_BASE                        32783
#define IDC_EXPRESSION                  32784
#define IDC_CUNNINGHAM_WIZARD           32785
#define IDC_FACTOR_WITH_Pm1             32786
#define IDC_FACTOR_WITH_Rho             32787
#define IDC_FACTOR_WITH_ECM             32788
#define IDC_USE_TRAY_ICON               32789
#define IDC_HIDE_THE_APP                32790
#define IDC_PREFERENCES                 32791
#define IDC_ABOUT_CONTENTS              32792
#define IDC_ABOUT_RECORDS               32793
#define IDC_RANGE_INFO                  32795
#define IDC_VERBOSE_SCREEN              32796
#define IDC_VERBOSE_FILE                32797
#define IDC_CERTIFICATES_NONE           32798
#define IDC_CERTIFICATES_BRIEF          32799
#define IDC_CERTIFICATES_VERBOSE        32800
#define IDC_CERTIFICATES_DELETE_COMPOSITES 32801
#define IDC_CERTIFICATES_DELETE_COMPOSITES_WITHOUT_FACTORS 32802
#define IDC_CERTIFICATES_NEVER_DELETE   32803
#define IDC_PRINT_DATE_IN_OUTPUT        32804
#define IDC_VIEW_STARTUPLOG             32805
#define IDC_EDIT_LOG                    32806
#define ID_MODE_FILEWITHVARIABLES       32807
#define IDC_IDLE                        32812
#define IDC_BELOW_NORMAL                32813
#define IDC_LOW                         32814
#define IDC_NORMAL                      32815
#define IDC_SET_PRP_BASE                32816
#define IDC_Pp1Np1_PROOFCHOICE          32817
#define IDC_FACTORIZE                   32818
#define IDC_FERMAT_FACTOR_ONLY          32819
#define IDC_CLEAR_HIGHLIGHT             32820
#define IDC_CLEAR_ALL                   32821
#define IDC_NORMAL_SCREEN               32822
#define IDC_QUIET_SCREEN                32823
#define IDC_GF_FACT_ONLY_SCREEN         32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
