
@echo off
echo If you have not yet shut Visual Studio, DO SO NOW.
pause
echo.
echo Deleting "base" temporary files.

call winclean1.bat

if exist pfgw.exe del pfgw.exe
if exist wincopy.exe del wincopy.exe
if exist wincopy.obj del wincopy.obj
if exist winpfgw.exe del winpfgw.exe
if exist pfgw_serverv2.exe del pfgw_serverv2.exe
if exist pfgw_serverv2.ini del pfgw_serverv2.ini
if exist buildlog.htm del buildlog.htm
if exist test\pf*.* del test\pf*.*
for %%f in (PFGW-ServerV2-Default*.*) do del PFGW-ServerV2-Default*.*

: These are generated by "./configure" in a Linux/Unix/Cygwin environment
if exist config.h      del config.h
if exist pflib.h       del pflib.h
if exist pfoo.h        del pfoo.h
if exist pfio.h        del pfio.h
if exist pfmath.h      del pfmath.h
if exist pfgwlib.h     del pfgwlib.h
if exist pfglue.h      del pfglue.h
if exist prmsieve.h    del prmsieve.h
if exist stdtypes.h    del stdtypes.h

: These are just extra crap files
if exist NetWork2.wip  del NetWork2.wip
if exist NetWork2.don  del NetWork2.don
if exist pfgw.out      del pfgw.out
if exist pfgw.log      del pfgw.log

: make sure there is an *.scc file, then attrib all to be read-write (recursively)
echo. > xx.scc
attrib -r *.scc /s > nul

: now nuke all of these file types in the base folder.
for %%f in (*.scc *.plg *.pos *.aps *.ncb *.pdb *.ilk *.idb *.map *.pch *.a) do del %%f

echo Deleting "pfconfig\headers" temporary files.
cd pfconfig\headers
: only delete these 2 files now.  Not the other "base" files. those file will
: always stay in this folder, and are not deleted. Wincopy does not copy them
if exist gmp.h         del gmp.h
if exist winbloz_msg.h del winbloz_msg.h
if exist zconf.h       del zconf.h
if exist zlib.h        del zlib.h

echo Deleting "pfconfig\objects" temporary files.
cd ..\..\pfconfig\objects
call ..\..\winclean1.bat
for %%f in (*.lib) do del *.lib
for %%f in (*.obj) do del *.obj

echo Deleting "pform\pfglue" temporary files.
cd ..\..\pform\pfglue
call ..\..\winclean1.bat

echo Deleting "pform\pfgw" temporary files.
cd ..\..\pform\pfgw
call ..\..\winclean1.bat

echo Deleting "pform\pfgwlib" temporary files.
cd ..\..\pform\pfgwlib
call ..\..\winclean1.bat

echo Deleting "pform\pflib" temporary files.
cd ..\..\pform\pflib
call ..\..\winclean1.bat

echo Deleting "pform\pfmath" temporary files.
cd ..\..\pform\pfmath
call ..\..\winclean1.bat

echo Deleting "pform\pfoo" temporary files.
cd ..\..\pform\pfoo
call ..\..\winclean1.bat

echo Deleting "pform\prmsieve" temporary files.
cd ..\..\pform\prmsieve
call ..\..\winclean1.bat

echo Deleting "pform\prmsieve\arith" temporary files.
cd arith
call ..\..\..\winclean1.bat
cd ..

echo Deleting "pform\prmsieve\atkins" temporary files.
cd atkins
call ..\..\..\winclean1.bat
cd ..

echo Deleting "pform\prmsieve\compress" temporary files.
cd compress
call ..\..\..\winclean1.bat
cd ..

echo Deleting "pform\prmsieve\erat" temporary files.
cd erat
call ..\..\..\winclean1.bat
cd ..

echo Deleting "pform\prmsieve\tables" temporary files.
cd tables
call ..\..\..\winclean1.bat
cd ..

echo Deleting "pform\pfio" temporary files.
cd ..\..\pform\pfio
call ..\..\winclean1.bat

cd ..

REM currently WinPFGW does not exist any  place other than on JimF's PC's
if not exist WinPFGW\nul goto skip_WinPFGW
echo Deleting "pform\WinPFGW" temporary files.
cd WinPFGW
call ..\..\winclean1.bat
cd ..
:skip_WinPFGW

REM currently PFGW_ServerV2 does not exist any  place other than on JimF's PC's
if not exist PFGW_ServerV2\nul goto skip_PFGW_ServerV2
echo Deleting "pform\PFGW_ServerV2" temporary files.
cd PFGW_ServerV2
call ..\..\winclean1.bat
cd ..
:skip_PFGW_ServerV2

REM currently APSieve does not exist any  place other than on JimF's PC's
if not exist APSieve\nul goto skip_APSieve
echo Deleting "pform\APSieve" temporary files.
cd APSieve
call ..\..\winclean1.bat
cd ..
:skip_APSieve


REM currently nutkrakr does not exist any  place other than on JimF's PC's
if not exist nutkrakr\nul goto skip_nutkrakr
echo Deleting "pform\nutkrakr" temporary files.
cd nutkrakr
call ..\..\winclean1.bat
cd ..
:skip_nutkrakr

cd ..


echo Done!
