include ../Makedefs

OBJS=math16.o
CSRC=math16.c

all: objs

objs: ${OBJS}

depend:
	-${MAKEDEPEND} ${CSRC}

clean:
	-rm ${OBJS}

math16.o: math16.c
	${CC} ${CC_OUT} $@ ${CC_INP} $<

# dont actually need 32 bit stuff yet
math32.o: math32.c
	${CC} ${CC_OUT} $@ ${CC_INP} $<

include ${MAKEDEPFILE}
